# .sops.yaml (Team Version)
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    #YAML list of all public keys
    age: |
      age1c8uz8qzz095uspf99rfpketpcl9fk3zpwtjkts0nx4tyxctjqdyspqzj36